services:
  app:
    build: .
    volumes:
      - '.:/app'
      - '${CACHE_PATH}:/root/.cache'
      - '${NLTK_DATA_PATH}:/root/nltk_data'
      - '${TEMP_PERSISTENCE_PATH}:/tmp'
    ports:
      - '${APP_PORT}:8000'
    command:
      - /bin/bash
      - -c
      - uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  ds-1:
    image: postgres:latest
    volumes:
      - ./ds-1.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - 'POSTGRES_USER=${DS_1_USER}'
      - 'POSTGRES_PASSWORD=${DS_1_PASSWORD}'
      - 'POSTGRES_DB=${DS_1_DATABASE}'
    ports:
      - '${DS_1_PORT}:5432'
  ds-2:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
    ports:
      - '${DS_2_PORT_1}:9200'
      - '${DS_2_PORT_2}:9600'
  ds-2-management:
    image: opensearchproject/opensearch-dashboards:latest
    environment:
      - 'OPENSEARCH_HOSTS=["https://ds-2:9200"]'
    ports:
      - '${DS_2_MANAGEMENT_PORT}:5601'